services:
  quart_server:
    image: quart_server
    container_name: quart_server
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 quart_server.py "
      ]
    env_file: .env
    ports:
      - 5678:5678
      - 5000:5000

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${SMSC_REDIS_PASSWORD}
    volumes:
      - type: volume
        source: redis_cache
        target: /data
volumes:
  redis_cache:
